### ISSUE TITLE
我在使用pacman导入key时遇到了问题

### ISSUE THREAD

**Issue by YikMengLam** [AzureZeng/wsl-arch-rootfs#2]
![image](https://github.com/user-attachments/assets/a1139bef-1c01-477f-939f-4a6e9de5867f)

error: restricting filesystem access failed because landlock is not supported by the kernel!

**Comment by AzureZeng** [comment]
The `pacman` v7.0 uses some security features that is introduced in newer Linux kernel version, which is not supported by the Linux kernel bundled in WSL (v5.15).

Solution 1:
Enable the `DisableSandbox` option in `/etc/pacman.conf`.

```conf
#UseSyslog
Color
#NoProgressBar
CheckSpace
#VerbosePkgLists
ParallelDownloads = 5
DownloadUser = alpm
DisableSandbox
```

Solution 2:
Use any Linux kernel version 6.6 or newer by compiling custom kernel and editing `~\.wslconfig`.
Maybe you can get the pre-compiled latest Linux LTS kernel in [here](https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling-LTS).

Hint: Recently Microsoft tried to update the kernel version to 6.6, but they met some problems, then reverted the kernel version. Maybe WSL can get official Linux LTS 6.6 kernel bundled soon.
